myFunction([
{
"hrvatski":"dobivati","deutsch":"bekommen",
"ja":"dobivam","ich":"bekomme",
"ti":"dobivaš","du":"bekommst",
"on":"dobiva","er":"bekommt",
"mi":"dobivamo","wir":"bekommen",
"vi":"dobivate","ihr":"bekommt",
"oni":"dobivaju","sie":"bekommen"
},
{
"hrvatski":"vjerovati","deutsch":"glauben",
"ja":"vjerujem","ich":"glaube",
"ti":"vjeruješ","du":"glaubst",
"on":"vjeruje","er":"glaubt",
"mi":"vjerujemo","wir":"glauben",
"vi":"vjerujete","ihr":"glaubt",
"oni":"vjeruju","sie":"glauben"
},
{
"hrvatski":"praviti","deutsch":"machen",
"ja":"pravim","ich":"mache",
"ti":"praviš","du":"machst",
"on":"pravi","er":"macht",
"mi":"pravimo","wir":"machen",
"vi":"pravite","ihr":"macht",
"oni":"prave","sie":"machen"
},
{
"hrvatski":"misliti","deutsch":"denken",
"ja":"mislim","ich":"denke",
"ti":"misliš","du":"denkst",
"on":"misli","er":"denkt",
"mi":"mislimo","wir":"denken",
"vi":"mislite","ihr":"denkt",
"oni":"misle","sie":"denken"
},
{
"hrvatski":"putovati","deutsch":"reisen",
"ja":"putujem","ich":"reise",
"ti":"putuješ","du":"reist",
"on":"putuje","er":"reist",
"mi":"putujemo","wir":"reisen",
"vi":"putujete","ihr":"reist",
"oni":"putuju","sie":"reisen"
},
{
"hrvatski":"razumjeti","deutsch":"verstehen",
"ja":"razumijem","ich":"verstehe",
"ti":"razumiješ","du":"verstehst",
"on":"razumije","er":"versteht",
"mi":"razumijemo","wir":"verstehen",
"vi":"razumijete","ihr":"versteht",
"oni":"razumiju","sie":"verstehen"
},
{
"hrvatski":"pisati","deutsch":"schreiben",
"ja":"pišem","ich":"schreibe",
"ti":"pišeš","du":"schreibst",
"on":"piše","er":"schreibt",
"mi":"pišemo","wir":"schreiben",
"vi":"pišete","ihr":"schreibt",
"oni":"pišu","sie":"schreiben"
},
{
"hrvatski":"čitati","deutsch":"lesen",
"ja":"čitam","ich":"lese",
"ti":"čitaš","du":"liest",
"on":"čita","er":"liest",
"mi":"čitamo","wir":"lesen",
"vi":"čitate","ihr":"lest",
"oni":"čitaju","sie":"lesen"
},
{
"hrvatski":"plivati","deutsch":"schwimmen"
,"ja":"plivam","ich":"schwimme",
"ti":"plivaš","du":"schwimmst",
"on":"pliva","er":"schwimmt",
"mi":"plivamo","wir":"schwimmen",
"vi":"plivate","ihr":"schwimmt",
"oni":"plivaju","sie":"schwimmen"
},
{
"hrvatski":"spavati","deutsch":"schlafen",
"ja":"spavam","ich":"schlafe",
"ti":"spavaš","du":"schläfst",
"on":"spava","er":"schläft",
"mi":"spavamo","wir":"schlafen",
"vi":"spavate","ihr":"schlaft",
"oni":"spavaju","sie":"schlafen"
},
{
"hrvatski":"kuhati","deutsch":"kochen",
"ja":"kuham","ich":"koche",
"ti":"kuhaš","du":"kochst",
"on":"kuha","er":"kocht",
"mi":"kuhamo","wir":"kochen",
"vi":"kuhate","ihr":"kocht",
"oni":"kuhaju","sie":"kochen"
},
{
"hrvatski":"pomagati","deutsch":"helfen",
"ja":"pomažem","ich":"helfe",
"ti":"pomažeš","du":"hilfst",
"on":"pomaže","er":"hilft",
"mi":"pomažemo","wir":"helfen",
"vi":"pomažete","ihr":"helft",
"oni":"pomažu","sie":"helfen"
},
{
"hrvatski":"dolaziti","deutsch":"kommen",
"ja":"dolazim","ich":"komme",
"ti":"dolaziš","du":"kommst",
"on":"dolazi","er":"kommt",
"mi":"dolazimo","wir":"kommen",
"vi":"dolazite","ihr":"kommt",
"oni":"dolaze","sie":"kommen"
},
{
"hrvatski":"prodaviti","deutsch":"verkaufen",
"ja":"prodajem","ich":"verkaufe",
"ti":"prodaješ","du":"verkaufst",
"on":"prodaje","er":"verkauft",
"mi":"prodajemo","wir":"verkaufen",
"vi":"prodajete","ihr":"verkauft","oni":"prodaju","sie":"verkaufen"
},
{
"hrvatski":"znati","deutsch":"wissen",
"ja":"znam","ich":"weiß",
"ti":"znaš","du":"weißt",
"on":"zna","er":"weiß",
"mi":"znamo","wir":"wissen",
"vi":"znate","ihr":"wisst",
"oni":"znaju","sie":"wissen"
},
{
"hrvatski":"pitati","deutsch":"fragen",
"ja":"pitam","ich":"frage",
"ti":"pitaš","du":"fragst",
"on":"pita","er":"fragt",
"mi":"pitamo","wir":"fragen",
"vi":"pitate","ihr":"fragt",
"oni":"pitaju","sie":"fragen"
},
{
"hrvatski":"raditi","deutsch":"arbeiten",
"ja":"radim","ich":"arbeite",
"ti":"radiš","du":"arbeitest",
"on":"radi","er":"arbeitet",
"mi":"radimo","wir":"arbeiten",
"vi":"radite","ihr":"arbeitet",
"oni":"rade","sie":"arbeiten"
},
{
"hrvatski":"piti","deutsch":"trinken",
"ja":"pijem","ich":"trinke",
"ti":"piješ","du":"trinkst",
"on":"pije","er":"trinkt",
"mi":"pijemo","wir":"trinken",
"vi":"pijete","ihr":"trinkt",
"oni":"piju","sie":"trinken"
},
{
"hrvatski":"kupovati","deutsch":"kaufen",
"ja":"kupujem","ich":"kaufe",
"ti":"kupuješ","du":"kaufst",
"on":"kupuje","er":"kauft",
"mi":"kupujemo","wir":"kaufen",
"vi":"kupujete","ihr":"kauft",
"oni":"kupuju","sie":"kaufen"
},
{
"hrvatski":"sjediti","deutsch":"sitzen",
"ja":"sjedim","ich":"sitze",
"ti":"sjediš","du":"sitzt",
"on":"sjedi","er":"sitzt",
"mi":"sjedimo","wir":"sitzen",
"vi":"sjedite","ihr":"sitzt",
"oni":"sjede","sie":"sitzen"
},
{
"hrvatski":"slušati","deutsch":"hören",
"ja":"slušam","ich":"höre",
"ti":"slušaš","du":"hörst",
"on":"sluša","er":"hört",
"mi":"slušamo","wir":"hören",
"vi":"slušate","ihr":"hört",
"oni":"slušaju","sie":"hören"
},
{
"hrvatski":"imati","deutsch":"haben",
"ja":"imam","ich":"habe",
"ti":"imaš","du":"hast",
"on":"ima","er":"hat",
"mi":"imamo","wir":"haben",
"vi":"imate","ihr":"habt",
"oni":"imaju","sie":"haben"
},
{
"hrvatski":"biti","deutsch":"sein",
"ja":"sam","ich":"bin",
"ti":"si","du":"bist",
"on":"je","er":"ist",
"mi":"smo","wir":"sind",
"vi":"ste","ihr":"seid",
"oni":"su","sie":"sind"
},
{
"hrvatski":"čistiti","deutsch":"putzen",
"ja":"čistim","ich":"putze",
"ti":"čistiš","du":"putzt",
"on":"čisti","er":"putzt",
"mi":"čistimo","wir":"putzen",
"vi":"čistite","ihr":"putzt",
"oni":"čiste","sie":"putzen"
},
{
"hrvatski":"odgovarati","deutsch":"antworten",
"ja":"odgovaram","ich":"antworte",
"ti":"odgovaraš","du":"antwortest",
"on":"odgovara","er":"antwortet",
"mi":"odgovaramo","wir":"antworten",
"vi":"odgovarate","ihr":"antwortet",
"oni":"odgovaraju","sie":"antworten"
},
{
"hrvatski":"jesti","deutsch":"essen",
"ja":"jedem","ich":"esse",
"ti":"jedeš","du":"ißt",
"on":"jede","er":"ißt",
"mi":"jedemo","wir":"essen",
"vi":"jedete","ihr":"eßt",
"oni":"jedu","sie":"essen"
},
{
"hrvatski":"stajati","deutsch":"stehen",
"ja":"stojim","ich":"stehe",
"ti":"stojiš","du":"stehst",
"on":"stoji","er":"steht",
"mi":"stojimo","wir":"stehen",
"vi":"stojite","ihr":"steht",
"oni":"stoje","sie":"stehen"
},
{
"hrvatski":"pokazivati","deutsch":"zeigen",
"ja":"pokazujem","ich":"zeige",
"ti":"pokazuješ","du":"zeigst",
"on":"pokazuje","er":"zeigt",
"mi":"pokazujemo","wir":"zeigen",
"vi":"pokazujete","ihr":"zeigt",
"oni":"pokazuju","sie":"zeigen"
},
{
"hrvatski":"prevoditi","deutsch":"übersetzen",
"ja":"prevodim","ich":"übersetze",
"ti":"prevodiš","du":"übersetzt",
"on":"prevodi","er":"übersetzt",
"mi":"prevodimo","wir":"übersetzen",
"vi":"prevodite","ihr":"übersetzt",
"oni":"prevode","sie":"übersetzen"
},
{
"hrvatski":"vidjeti","deutsch":"sehen",
"ja":"vidim","ich":"sehe",
"ti":"vidiš","du":"siehst",
"on":"vidi","er":"sieht",
"mi":"vidimo","wir":"sehen",
"vi":"vidite","ihr":"seht",
"oni":"vide","sie":"sehen"
},
{
"hrvatski":"htjeti","deutsch":"wollen",
"ja":"hoću","ich":"will",
"ti":"hoćeš","du":"willst",
"on":"hoće","er":"will",
"mi":"hoćemo","wir":"wollen",
"vi":"hoćete","ihr":"wollt",
"oni":"hoće","sie":"wollen"
},
{
"hrvatski":"ići","deutsch":"gehen",
"ja":"idem","ich":"gehe",
"ti":"ideš","du":"gehst",
"on":"ide","er":"geht",
"mi":"idemo","wir":"gehen",
"vi":"idete","ihr":"geht",
"oni":"idu","sie":"gehen"
},
{
"hrvatski":"živjeti","deutsch":"leben",
"ja":"živim","ich":"lebe",
"ti":"živiš","du":"lebst",
"on":"živi","er":"lebt",
"mi":"živimo","wir":"leben",
"vi":"živite","ihr":"lebt",
"oni":"žive","sie":"leben"
},
{
"hrvatski":"moći","deutsch":"können",
"ja":"mogu","ich":"kann",
"ti":"možeš","du":"kannst",
"on":"može","er":"kann",
"mi":"možemo","wir":"können",
"vi":"možete","ihr":"könnt",
"oni":"mogu","sie":"können"
},
{
"hrvatski":"voljeti","deutsch":"lieben",
"ja":"volim","ich":"liebe",
"ti":"voliš","du":"liebst",
"on":"voli","er":"liebt",
"mi":"volimo","wir":"lieben",
"vi":"volite","ihr":"liebt",
"oni":"vole","sie":"lieben"
},
{
"hrvatski":"telefonirati","deutsch":"telefonieren",
"ja":"telefoniram","ich":"telefoniere",
"ti":"telefoniraš","du":"telefonierst",
"on":"telefonira","er":"telefoniert",
"mi":"telefoniram","wir":"telefonieren",
"vi":"telefonirate","ihr":"telefoniert",
"oni":"telefoniraju","sie":"telefonieren"
},
{
"hrvatski":"voziti","deutsch":"fahren",
"ja":"vozim","ich":"fahre",
"ti":"voziš","du":"fährst",
"on":"vozi","er":"fährt",
"mi":"vozimo","wir":"fahren",
"vi":"vozite","ihr":"fahrt",
"oni":"voze","sie":"fahren"
},
{
"hrvatski":"davati","deutsch":"geben",
"ja":"dajem","ich":"gebe",
"ti":"daješ","du":"gibst",
"on":"daje","er":"gibt",
"mi":"dajemo","wir":"geben",
"vi":"dajete","ihr":"gebt",
"oni":"daju","sie":"geben"
},
{
"hrvatski":"govoriti","deutsch":"sprechen",
"ja":"govorim","ich":"spreche",
"ti":"govoriš","du":"sprichst",
"on":"govori","er":"spricht",
"mi":"govorimo","wir":"sprechen",
"vi":"govorite","ihr":"sprecht",
"oni":"govore","sie":"sprechen"
}
])